services:
  octopus:
    image: lingyuins/octopus:v1.1.0
    container_name: octopus
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      OCTOPUS_AUTH_JWT_SECRET: "change-this-to-a-long-random-secret"
